import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { GeneratedFile } from '@/types';

// ─────────────────────────────────────────────────────────────────────────────
// Short slug generator
// Takes up to 3 meaningful words from any string input.
// "SaaS dashboard with auth and payments" → "saas-dashboard-auth"
// ─────────────────────────────────────────────────────────────────────────────

const STOP_WORDS = new Set([
  'a', 'an', 'the', 'and', 'or', 'but', 'for', 'nor', 'so', 'yet',
  'with', 'to', 'in', 'on', 'at', 'by', 'up', 'as', 'is', 'it',
  'of', 'from', 'into', 'via', 'that', 'this', 'these', 'those',
  'build', 'create', 'make', 'generate', 'write', 'develop',
  'using', 'use', 'add', 'implement', 'include',
]);

function makeShortSlug(input: string, maxWords = 3): string {
  if (!input?.trim()) return 'nexus-project';

  const words = input
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, ' ')
    .split(/\s+/)
    .map((w) => w.replace(/^-+|-+$/g, ''))
    .filter((w) => w.length >= 3 && !STOP_WORDS.has(w));

  const chosen = words.slice(0, maxWords);
  if (chosen.length === 0) return 'nexus-project';
  return chosen.join('-');
}

// ─────────────────────────────────────────────────────────────────────────────
// File stats
// ─────────────────────────────────────────────────────────────────────────────

function getFileStats(files: GeneratedFile[]) {
  const totalLines = files.reduce((s, f) => s + f.linesAdded, 0);
  const totalBytes = files.reduce(
    (s, f) => s + new TextEncoder().encode(f.content).length,
    0,
  );
  const byAgent = files.reduce<Record<string, number>>((acc, f) => {
    acc[f.agentName] = (acc[f.agentName] ?? 0) + 1;
    return acc;
  }, {});

  return { totalLines, totalBytes, byAgent };
}

// ─────────────────────────────────────────────────────────────────────────────
// Main download function
// ─────────────────────────────────────────────────────────────────────────────

export async function downloadZip(
  files: GeneratedFile[],
  projectName: string,
): Promise<void> {
  const zip  = new JSZip();
  const slug = makeShortSlug(projectName);
  const { totalLines, totalBytes, byAgent } = getFileStats(files);

  // ── README ──────────────────────────────────────────────────────────────

  const agentList = Object.entries(byAgent)
    .sort(([, a], [, b]) => b - a)
    .map(([name, count]) => `- **${name}**: ${count} file${count !== 1 ? 's' : ''}`)
    .join('\n');

  const readme = `# ${slug}

> Generated by **NexusAI Team** — 15 specialized AI agents

## Stats
- **Files**: ${files.length}
- **Total lines**: ${totalLines.toLocaleString()}
- **Size**: ${(totalBytes / 1024).toFixed(1)} KB

## Agents
${agentList}

## Quick Start
\`\`\`bash
npm install
npm run dev
\`\`\`

## Build
\`\`\`bash
npm run build
npm start
\`\`\`

---
*Generated at ${new Date().toISOString()}*
`;

  zip.file('README.md', readme);

  // ── Files ────────────────────────────────────────────────────────────────

  const seen = new Set<string>();
  let collisions = 0;

  for (const f of files) {
    let path = f.filename;

    if (seen.has(path)) {
      collisions++;
      const ext   = path.includes('.') ? path.slice(path.lastIndexOf('.')) : '';
      const base  = path.slice(0, path.lastIndexOf('.'));
      path = `${base}_${f.agentId}_${collisions}${ext}`;
    }

    seen.add(path);
    zip.file(path, f.content);
  }

  // ── Compress and save ────────────────────────────────────────────────────

  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 7 },
  });

  // Zip filename: short slug only (max 3 words)
  saveAs(blob, `${slug}.zip`);
}