import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { GeneratedFile } from '@/types';

export async function downloadZip(files: GeneratedFile[], projectName: string) {
  const zip  = new JSZip();
  const slug = (projectName || 'nexus-project').replace(/\s+/g, '-').toLowerCase();

  zip.file('package.json', JSON.stringify({
    name: slug, version: '1.0.0', private: true,
    scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
    dependencies: { next: '14.2.5', react: '^18', 'react-dom': '^18', tailwindcss: '^3' },
  }, null, 2));

  zip.file('README.md', `# ${projectName}\n\nGenerated by **NexusAI Team**.\n\n\`\`\`bash\nnpm install && npm run dev\n\`\`\`\n`);

  const seen = new Set<string>();
  for (const f of files) {
    const path = seen.has(f.filename)
      ? f.filename.replace(/(\.[^.]+)$/, `_${f.agentId}$1`)
      : f.filename;
    seen.add(path);
    zip.file(path, f.content);
  }

  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
  saveAs(blob, `${slug}.zip`);
}
