// codegen.ts — faqat CODE_SNIPPETS va generateFallbackFilename eksport qiladi
// FILE_NAMES endi useCodegen.ts ichida dinamik quriladi (project type ga qarab)
// Bu fayl eski kodni import qilgan joylari uchun saqlanadi

export const CODE_SNIPPETS: Record<number, string[]> = {
  1: [
    `const Card = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div className="rounded-2xl border border-white/10 bg-black/40 backdrop-blur-xl p-6 shadow-xl">
    <h3 className="font-mono text-sm tracking-widest text-purple-400 uppercase mb-3">{title}</h3>
    {children}
  </div>
);`,
  ],
  2: [
    `export function useDebounce<T>(value: T, delay: number): T {
  const [debounced, setDebounced] = useState<T>(value);
  useEffect(() => {
    const t = setTimeout(() => setDebounced(value), delay);
    return () => clearTimeout(t);
  }, [value, delay]);
  return debounced;
}`,
  ],
  3: [
    `export async function POST(req: NextRequest) {
  const { model, messages } = await req.json();
  if (!model) return NextResponse.json({ error: 'model required' }, { status: 400 });
  return NextResponse.json(await chatProxy({ model, messages }));
}`,
  ],
  4: [
    `model User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
}`,
  ],
  5: [
    `export function verifyJWT(token: string): JWTPayload {
  return jwt.verify(token, process.env.JWT_SECRET!) as JWTPayload;
}`,
  ],
  6: [
    `export const useAppStore = create<AppState>()((set) => ({
  theme: 'dark',
  setTheme: (t) => set({ theme: t }),
}));`,
  ],
  7: [
    `FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next ./.next
EXPOSE 3000
CMD ["node_modules/.bin/next", "start"]`,
  ],
  8: [
    `/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };
export default nextConfig;`,
  ],
  9: [
    `export const fadeIn = {
  hidden: { opacity: 0, y: 20 },
  show:   { opacity: 1, y: 0, transition: { type: 'spring', damping: 20 } },
};`,
  ],
  10: [
    `const res = await fetch('/api/models');
if (!res.ok) throw new Error(\`HTTP \${res.status}\`);
const data = await res.json();`,
  ],
  11: [
    `describe('API /chat', () => {
  it('returns 400 when model is missing', async () => {
    const res = await fetch('/api/chat', { method: 'POST', body: '{}' });
    expect(res.status).toBe(400);
  });
});`,
  ],
  12: [
    `# Project\n\nGenerated by **NexusAI Team**.\n\n\`\`\`bash\nnpm install && npm run dev\n\`\`\``,
  ],
  13: [
    `const memoized = useMemo(() => expensiveCalc(data), [data]);
const stable   = useCallback((id: string) => dispatch({ type: 'SELECT', id }), []);`,
  ],
  14: [
    `paths:
  /api/users:
    get:
      summary: List users
      responses:
        200:
          description: Success`,
  ],
  15: [
    `export const metadata: Metadata = {
  title: 'App',
  description: 'Generated by NexusAI',
};`,
  ],
};

// FILE_NAMES endi ishlatilmaydi — useCodegen.ts da dinamik quriladi
// Eski importlar uchun bo'sh export
export const FILE_NAMES: Record<number, string[]> = {};

interface AgentMeta { id: number; name: string; }

export function generateFallbackFilename(agent: AgentMeta, suffix: number): string {
  return `src/modules/agent${agent.id}/module${suffix}.ts`;
}