'use client';
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { MonitorPlay, Download, FolderOpen, FileCode2, CheckCircle } from 'lucide-react';
import { useAppStore } from '@/store/appStore';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';

interface PreviewCanvasProps { onDownload: () => void; }

export function PreviewCanvas({ onDownload }: PreviewCanvasProps) {
  const { isSynthesized, generatedFiles, progress } = useAppStore();
  const [activeFile, setActiveFile] = useState<number | null>(null);

  // Group files by agent
  const byAgent = generatedFiles.reduce<Record<number, typeof generatedFiles>>((acc, f) => {
    (acc[f.agentId] ??= []).push(f);
    return acc;
  }, {});

  return (
    <div className="relative flex flex-col w-full rounded-2xl border border-white/10 bg-slate-900/50 backdrop-blur-xl shadow-2xl overflow-hidden h-full">
      {/* Header */}
      <div className="flex items-center gap-3 px-4 py-3 border-b border-white/10 bg-gradient-to-r from-slate-900/50 to-indigo-950/50 flex-shrink-0">
        <MonitorPlay className="w-4 h-4 text-emerald-400" />
        <h2 className="text-sm font-title tracking-widest text-white font-bold">LIVE BUILD</h2>
        <div className="ml-auto flex items-center gap-2">
          {isSynthesized && (
            <>
              <CheckCircle className="w-3.5 h-3.5 text-emerald-400" />
              <Badge label="DONE" color="#4ade80" />
            </>
          )}
          {isSynthesized && (
            <Button variant="success" size="sm" onClick={onDownload}>
              <Download className="w-3.5 h-3.5" /> Download ZIP
            </Button>
          )}
        </div>
      </div>

      {/* Body */}
      <div className="flex-1 overflow-y-auto min-h-0 hide-scrollbar">
        <AnimatePresence mode="wait">
          {!isSynthesized ? (
            <motion.div
              key="waiting"
              initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              className="flex flex-col items-center justify-center h-full gap-4 p-8 text-slate-500"
            >
              <div
                className="w-28 h-28 rounded-full border-2 border-dashed border-slate-700 flex items-center justify-center animate-spin-slow"
              >
                <MonitorPlay className="w-10 h-10 opacity-20" />
              </div>
              <div className="text-center">
                <p className="text-sm font-mono">Canvas compiles after generation</p>
                <p className="text-xs text-indigo-400/50 mt-1">
                  {generatedFiles.length > 0 ? `${generatedFiles.length} files built… ${progress}%` : 'Start building to see output'}
                </p>
              </div>
              {/* Live mini file list */}
              {generatedFiles.length > 0 && (
                <div className="w-full max-w-xs space-y-1 mt-2">
                  {generatedFiles.slice(-6).map((f) => (
                    <motion.div
                      key={f.id}
                      initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }}
                      className="flex items-center gap-2 text-[10px] font-mono text-slate-500"
                    >
                      <div className="w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: f.agentColor }} />
                      <span className="truncate">{f.filename}</span>
                    </motion.div>
                  ))}
                </div>
              )}
            </motion.div>
          ) : (
            <motion.div
              key="done"
              initial={{ opacity: 0 }} animate={{ opacity: 1 }}
              className="p-4 space-y-3"
            >
              {/* Success banner */}
              <div className="flex items-center gap-3 p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20">
                <CheckCircle className="w-5 h-5 text-emerald-400 flex-shrink-0" />
                <div>
                  <p className="text-sm font-semibold text-emerald-300">Build Complete!</p>
                  <p className="text-xs text-emerald-600">{generatedFiles.length} files generated by 15 AI agents</p>
                </div>
              </div>

              {/* Files by agent */}
              {Object.entries(byAgent).map(([agentId, files]) => (
                <div key={agentId}>
                  <div
                    className="flex items-center gap-2 text-[10px] font-mono mb-1 cursor-pointer"
                    onClick={() => setActiveFile(activeFile === Number(agentId) ? null : Number(agentId))}
                  >
                    <FolderOpen className="w-3 h-3" style={{ color: files[0].agentColor }} />
                    <span style={{ color: files[0].agentColor }} className="font-bold tracking-widest">
                      {files[0].agentName}
                    </span>
                    <span className="text-slate-600">({files.length} files)</span>
                  </div>
                  <AnimatePresence>
                    {activeFile === Number(agentId) && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}
                        className="overflow-hidden"
                      >
                        <div className="pl-5 space-y-1 mb-2">
                          {files.map((f) => (
                            <div key={f.id} className="flex items-center gap-2 text-[10px] font-mono text-slate-500">
                              <FileCode2 className="w-3 h-3 text-slate-700 flex-shrink-0" />
                              <span className="truncate">{f.filename}</span>
                              <span className="ml-auto text-slate-700">+{f.linesAdded}L</span>
                            </div>
                          ))}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              ))}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
